development:
  host: localhost:8080
  email: ENV['LOCOMOTIVE_EMAIL']
  password: ENV['LOCOMOTIVE_PASSSWORD']
  api_key: b78473ec15d10323446f904e41653334613ccc33
staging:
  host: localhost:8080
  email: john@doe.net
  password: apassword
  # api_key: b78473ec15d10323446f904e41653334613ccc33
production:
  host: localhost:8080
  email: john@doe.net
  password: apassword
  # api_key: b78473ec15d10323446f904e41653334613ccc33